### ISSUE TITLE
编译不成功

### ISSUE THREAD

**Issue by daiwenbo88** [xiaoqiAndroid/LibJpegCompress#2]
你好 我这边导入你的工程 调用native方法 却报错 native方法未实现

**Comment by JavaNoober** [comment]
包名是不是被你修改了

**Comment by songsh** [comment]
java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String com.xiaoqi.libjpegcompress.ImageUtils.compressBitmap(android.graphics.Bitmap, int, int, int, byte[], boolean) (tried Java_com_xiaoqi_libjpegcompress_ImageUtils_compressBitmap and Java_com_xiaoqi_libjpegcompress_ImageUtils_compressBitmap__Landroid_graphics_Bitmap_2III_3BZ)

**Comment by JavaNoober** [comment]
我重新提交了新的so文件，现在应该是可以直接用了。
