### ISSUE TITLE
兼容性问题

### ISSUE THREAD

**Issue by songsh** [xiaoqiAndroid/LibJpegCompress#3]
是用huffman压缩吗，还有只支持arm的？

**Comment by JavaNoober** [comment]
是huffman压缩，只支持arm

**Comment by songsh** [comment]
为什么不支持其它平台，你有源码可以编译的？

**Comment by JavaNoober** [comment]
@songsh 我有的源码也只支持arm啊。如果真的想让x86的也能用，那就把你的libs全都删了，只剩下armeabi文件夹，这样x86的机型应该就会去直接调用armeabi下的so。你可以去解压缩看一下qq 微信那些app，它们的lib只会有一个arm的文件夹，而不会出现x86的。这样能最大的保证兼容性
